# "/" + ä»“åº“çš„åå­—. èµ„æºæ–‡ä»¶çš„è·¯å¾„ç»„æˆéƒ¨åˆ†
baseurl: "/create-pet-template"

# ç½‘é¡µçš„æ ‡é¢˜
title: æˆ‘çš„ä¸ªäººä¸»é¡µ
# å†…å®¹é¡µæ ‡é¢˜
name: æˆ‘çš„å® ç‰© ğŸˆâ€â¬›

# ä¸ªäººæ˜µç§°
username: é˜¿ ç™½
# ä¸ªäººå¤´åƒ, å¯é€‰æ‹©: default.jpg | dinosaur.jpg | github-1.jpg | github-2.jpg | github-3.jpg
avatar: github-3.jpg
# ä¸ªäººç®€ä»‹ï¼Œ æ˜¾ç¤ºåœ¨é¡µé¢çš„æ˜µç§°æ­£ä¸‹æ–¹
description: å…¨æ ˆå·¥ç¨‹å¸ˆï¼Œ ä¸“æ³¨äº Mobile, TDD, DDD ç­‰

# å® ç‰©ç›¸å†Œå›¾åƒåœ°å€. å€¼ä¸º url æ ¼å¼
images:
  - https://cdn.jsdelivr.net/gh/sddtc/upic-cloud@main/images/2021/2021-02-28-zU68tY-AG9Oug.png

# å…¶å®ƒé…ç½®ï¼Œå¯å¿½ç•¥
sass:
  sass_dir: assets/_sass
  style: compressed
